import type { AppConfig } from '../config/env.js';
import type { HarnessConfig } from '@harnesskit/core';

const optionalString = (value: string | undefined) => (value ? value : undefined);

/** Runtime-mutable fields mirrored from AppConfig into the live HarnessConfig object. */
const RUNTIME_SYNC_KEYS = [
  'OPENAI_BASE_URL',
  'OPENAI_API_KEY',
  'OPENAI_MODEL',
  'OPENAI_REASONING_EFFORT',
  'WEB_SEARCH_MODE',
  'WEB_SEARCH_PROVIDERS',
  'OPENAI_NATIVE_WEB_SEARCH',
  'TAVILY_API_KEY',
  'SERPER_API_KEY',
  'BRAVE_SEARCH_API_KEY',
  'OPENAI_NATIVE_IMAGE_GENERATION',
  'IMAGE_PROVIDERS',
  'OPENAI_IMAGE_API_KEY',
  'OPENAI_IMAGE_BASE_URL',
  'OPENAI_IMAGE_MODEL',
  'ZHIPU_IMAGE_API_KEY',
  'ZHIPU_IMAGE_BASE_URL',
  'ZHIPU_IMAGE_MODEL',
  'DASHSCOPE_IMAGE_API_KEY',
  'DASHSCOPE_IMAGE_BASE_URL',
  'DASHSCOPE_IMAGE_MODEL',
  'LLM_MAX_OUTPUT_TOKENS',
  'TOOL_MAX_OUTPUT_TOKENS',
  'ENABLE_ASSISTANT_TOOLS',
] as const satisfies ReadonlyArray<keyof AppConfig & keyof HarnessConfig>;

const buildRuntimeHarnessPatch = (config: AppConfig): Pick<HarnessConfig, (typeof RUNTIME_SYNC_KEYS)[number]> => ({
  OPENAI_BASE_URL: config.OPENAI_BASE_URL,
  OPENAI_API_KEY: config.OPENAI_API_KEY,
  OPENAI_MODEL: config.OPENAI_MODEL,
  OPENAI_REASONING_EFFORT: config.OPENAI_REASONING_EFFORT,
  WEB_SEARCH_MODE: config.WEB_SEARCH_MODE,
  WEB_SEARCH_PROVIDERS: optionalString(config.WEB_SEARCH_PROVIDERS),
  OPENAI_NATIVE_WEB_SEARCH: config.OPENAI_NATIVE_WEB_SEARCH,
  TAVILY_API_KEY: optionalString(config.TAVILY_API_KEY),
  SERPER_API_KEY: optionalString(config.SERPER_API_KEY),
  BRAVE_SEARCH_API_KEY: optionalString(config.BRAVE_SEARCH_API_KEY),
  OPENAI_NATIVE_IMAGE_GENERATION: config.OPENAI_NATIVE_IMAGE_GENERATION,
  IMAGE_PROVIDERS: optionalString(config.IMAGE_PROVIDERS),
  OPENAI_IMAGE_API_KEY: optionalString(config.OPENAI_IMAGE_API_KEY),
  OPENAI_IMAGE_BASE_URL: config.OPENAI_IMAGE_BASE_URL,
  OPENAI_IMAGE_MODEL: config.OPENAI_IMAGE_MODEL,
  ZHIPU_IMAGE_API_KEY: optionalString(config.ZHIPU_IMAGE_API_KEY),
  ZHIPU_IMAGE_BASE_URL: config.ZHIPU_IMAGE_BASE_URL,
  ZHIPU_IMAGE_MODEL: config.ZHIPU_IMAGE_MODEL,
  DASHSCOPE_IMAGE_API_KEY: optionalString(config.DASHSCOPE_IMAGE_API_KEY),
  DASHSCOPE_IMAGE_BASE_URL: config.DASHSCOPE_IMAGE_BASE_URL,
  DASHSCOPE_IMAGE_MODEL: config.DASHSCOPE_IMAGE_MODEL,
  LLM_MAX_OUTPUT_TOKENS: config.LLM_MAX_OUTPUT_TOKENS,
  TOOL_MAX_OUTPUT_TOKENS: config.TOOL_MAX_OUTPUT_TOKENS,
  ENABLE_ASSISTANT_TOOLS: config.ENABLE_ASSISTANT_TOOLS,
});

/** Keep HarnessKit's shared config object aligned with AppConfig after admin settings change. */
export const syncHarnessConfig = (config: AppConfig, harnessConfig: HarnessConfig): void => {
  Object.assign(harnessConfig, buildRuntimeHarnessPatch(config));
};

/** Map SkillChat AppConfig → HarnessKit HarnessConfig */
export const toHarnessConfig = (config: AppConfig): HarnessConfig => ({
  CWD: config.CWD,
  DATA_ROOT: config.DATA_ROOT,
  SKILLS_ROOT: config.SKILLS_ROOT,
  INSTALLED_SKILLS_ROOT: config.INSTALLED_SKILLS_ROOT,
  ...buildRuntimeHarnessPatch(config),
  MODEL_CONTEXT_WINDOW_TOKENS: config.MODEL_CONTEXT_WINDOW_TOKENS,
  MODEL_AUTO_COMPACT_TOKEN_LIMIT: config.MODEL_AUTO_COMPACT_TOKEN_LIMIT,
  LLM_REQUEST_TIMEOUT_MS: config.LLM_REQUEST_TIMEOUT_MS,
  STREAM_MAX_RETRIES: config.STREAM_MAX_RETRIES,
  STREAM_BACKOFF_BASE_MS: config.STREAM_BACKOFF_BASE_MS,
  STREAM_BACKOFF_MULTIPLIER: config.STREAM_BACKOFF_MULTIPLIER,
  ENABLE_TOKEN_TRACKING: config.ENABLE_TOKEN_TRACKING,
  ENABLE_REASONING_EVENTS: config.ENABLE_REASONING_EVENTS,
  IMAGE_THUMBNAIL_THRESHOLD_BYTES: config.IMAGE_THUMBNAIL_THRESHOLD_BYTES,
  IMAGE_THUMBNAIL_MAX_WIDTH: config.IMAGE_THUMBNAIL_MAX_WIDTH,
  IMAGE_THUMBNAIL_MAX_HEIGHT: config.IMAGE_THUMBNAIL_MAX_HEIGHT,
  IMAGE_THUMBNAIL_QUALITY: config.IMAGE_THUMBNAIL_QUALITY,
  MAX_CONCURRENT_RUNS: config.MAX_CONCURRENT_RUNS,
  RUN_TIMEOUT_MS: config.RUN_TIMEOUT_MS,
  NODE_ENV: config.NODE_ENV,
  INLINE_JOBS: config.INLINE_JOBS,
  productName: 'SkillChat',
});
