import type { AppConfig } from '../config/env.js';
import type { HarnessConfig } from '@harnesskit/core';

/** Runtime-mutable fields mirrored from AppConfig into the live HarnessConfig object. */
const RUNTIME_SYNC_KEYS = [
  'OPENAI_BASE_URL',
  'OPENAI_API_KEY',
  'OPENAI_MODEL',
  'OPENAI_REASONING_EFFORT',
  'OPENAI_NATIVE_WEB_SEARCH',
  'OPENAI_NATIVE_IMAGE_GENERATION',
  'LLM_MAX_OUTPUT_TOKENS',
  'TOOL_MAX_OUTPUT_TOKENS',
  'ENABLE_ASSISTANT_TOOLS',
] as const satisfies ReadonlyArray<keyof AppConfig & keyof HarnessConfig>;

/** Keep HarnessKit's shared config object aligned with AppConfig after admin settings change. */
export const syncHarnessConfig = (config: AppConfig, harnessConfig: HarnessConfig): void => {
  Object.assign(harnessConfig, {
    OPENAI_BASE_URL: config.OPENAI_BASE_URL,
    OPENAI_API_KEY: config.OPENAI_API_KEY,
    OPENAI_MODEL: config.OPENAI_MODEL,
    OPENAI_REASONING_EFFORT: config.OPENAI_REASONING_EFFORT,
    OPENAI_NATIVE_WEB_SEARCH: config.OPENAI_NATIVE_WEB_SEARCH,
    OPENAI_NATIVE_IMAGE_GENERATION: config.OPENAI_NATIVE_IMAGE_GENERATION,
    LLM_MAX_OUTPUT_TOKENS: config.LLM_MAX_OUTPUT_TOKENS,
    TOOL_MAX_OUTPUT_TOKENS: config.TOOL_MAX_OUTPUT_TOKENS,
    ENABLE_ASSISTANT_TOOLS: config.ENABLE_ASSISTANT_TOOLS,
  } satisfies Pick<HarnessConfig, (typeof RUNTIME_SYNC_KEYS)[number]>);
};

/** Map SkillChat AppConfig → HarnessKit HarnessConfig */
export const toHarnessConfig = (config: AppConfig): HarnessConfig => ({
  CWD: config.CWD,
  DATA_ROOT: config.DATA_ROOT,
  SKILLS_ROOT: config.SKILLS_ROOT,
  INSTALLED_SKILLS_ROOT: config.INSTALLED_SKILLS_ROOT,
  OPENAI_BASE_URL: config.OPENAI_BASE_URL,
  OPENAI_API_KEY: config.OPENAI_API_KEY,
  OPENAI_MODEL: config.OPENAI_MODEL,
  MODEL_CONTEXT_WINDOW_TOKENS: config.MODEL_CONTEXT_WINDOW_TOKENS,
  MODEL_AUTO_COMPACT_TOKEN_LIMIT: config.MODEL_AUTO_COMPACT_TOKEN_LIMIT,
  WEB_SEARCH_MODE: config.WEB_SEARCH_MODE,
  OPENAI_NATIVE_WEB_SEARCH: config.OPENAI_NATIVE_WEB_SEARCH,
  OPENAI_NATIVE_IMAGE_GENERATION: config.OPENAI_NATIVE_IMAGE_GENERATION,
  OPENAI_REASONING_EFFORT: config.OPENAI_REASONING_EFFORT,
  LLM_MAX_OUTPUT_TOKENS: config.LLM_MAX_OUTPUT_TOKENS,
  TOOL_MAX_OUTPUT_TOKENS: config.TOOL_MAX_OUTPUT_TOKENS,
  ENABLE_ASSISTANT_TOOLS: config.ENABLE_ASSISTANT_TOOLS,
  LLM_REQUEST_TIMEOUT_MS: config.LLM_REQUEST_TIMEOUT_MS,
  STREAM_MAX_RETRIES: config.STREAM_MAX_RETRIES,
  STREAM_BACKOFF_BASE_MS: config.STREAM_BACKOFF_BASE_MS,
  STREAM_BACKOFF_MULTIPLIER: config.STREAM_BACKOFF_MULTIPLIER,
  ENABLE_TOKEN_TRACKING: config.ENABLE_TOKEN_TRACKING,
  ENABLE_REASONING_EVENTS: config.ENABLE_REASONING_EVENTS,
  IMAGE_THUMBNAIL_THRESHOLD_BYTES: config.IMAGE_THUMBNAIL_THRESHOLD_BYTES,
  IMAGE_THUMBNAIL_MAX_WIDTH: config.IMAGE_THUMBNAIL_MAX_WIDTH,
  IMAGE_THUMBNAIL_MAX_HEIGHT: config.IMAGE_THUMBNAIL_MAX_HEIGHT,
  IMAGE_THUMBNAIL_QUALITY: config.IMAGE_THUMBNAIL_QUALITY,
  MAX_CONCURRENT_RUNS: config.MAX_CONCURRENT_RUNS,
  RUN_TIMEOUT_MS: config.RUN_TIMEOUT_MS,
  NODE_ENV: config.NODE_ENV,
  INLINE_JOBS: config.INLINE_JOBS,
  productName: 'SkillChat',
});
